language: android

jdk: oraclejdk8

sudo: false

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:                #Cache all dirs under .gradle folder
  - $HOME/.gradle/daemon      #Cache daemon logs
  - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
  - $HOME/.gradle/wrapper     #Cache the gradle

android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew

script:
- ./gradlew build connectedCheck
- ./gradlew clean build

deploy:
  provider: script
  script: ./gradlew bintrayUpload -PbintrayUser=bravecheng -PbintrayKey=$BINTRAY_API_KEY -PdryRun=false
  skip_cleanup: true
  dry-run: false
  on:
    branch: master